server:
  port: ${SERVER_PORT}

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}

webhook:
  baseUrl: ${WEBHOOK_URL}
  path: ${WEBHOOK_PATH}