server:
  port: 7575

database:
  host: localhost
  port: 5432
  user: techchallenge
  password: 123456
  name: tech_payment
  networks: postgres-network

webhook:
  baseUrl: localhost:8080
  path: /payment